#%%

import numpy as np
import scipy.io as sio
import scipy.linalg as sla
import matplotlib.pyplot as plt
import matplotlib.tri as tri
from matplotlib.collections import PolyCollection
import matplotlib.cm as cm
import sys, os

# ---------------------------------------------------------------------------
# Paste the three shape-function routines from LN_code_python.py here so
# the file is self-contained.  If LN_code_python.py is on the Python path
# you can replace these with:  from LN_code_python import ...
# ---------------------------------------------------------------------------

def _N_kirchoff_func(in1, in2, in3, in4, in5):
    """Kirchhoff plate shape functions N  (returns shape (12,1))."""
    xe11=in2[0,:]; xe12=in2[1,:]
    xe21=in3[0,:]; xe22=in3[1,:]
    xe31=in4[0,:]; xe32=in4[1,:]
    xe41=in5[0,:]; xe42=in5[1,:]
    xi1=in1[0,:];  xi2=in1[1,:]
    t2=xi1+1.0; t3=xi2+1.0; t4=xi1**2; t5=xi2**2
    t6=xi1-1.0; t7=xi2-1.0
    t8=t4*xe11; t9=t5*xe11; t10=t4*xe12; t11=t5*xe12
    t12=t4*xe21;t13=t5*xe21;t14=t4*xe22;t15=t5*xe22
    t16=t4*xe31;t17=t5*xe31;t18=t4*xe32;t19=t5*xe32
    t20=t4*xe41;t21=t5*xe41;t22=t4*xe42;t23=t5*xe42
    mt1=np.array([t6*t7*(t4+t5+t6+t7)*(-1./8.),
                  (t6*t7*(t8+t9-t12-t21-xe11*2.+xe21+xe41))/16.,
                  (t6*t7*(t10+t11-t14-t23-xe12*2.+xe22+xe42))/16.,
                  (t2*t7*(-t2+t4+t5+t7))/8.,
                  t2*t7*(-t8+t12+t13-t17+xe11-xe21*2.+xe31)*(-1./16.),
                  t2*t7*(-t10+t14+t15-t19+xe12-xe22*2.+xe32)*(-1./16.),
                  (t2*t3*(t2+t3-t4-t5))/8.,
                  (t2*t3*(-t13+t16+t17-t20+xe21-xe31*2.+xe41))/16.,
                  (t2*t3*(-t15+t18+t19-t22+xe22-xe32*2.+xe42))/16.])
    mt2=np.array([(t3*t6*(-t3+t4+t5+t6))/8.,
                  t3*t6*(-t9-t16+t20+t21+xe11+xe31-xe41*2.)*(-1./16.),
                  t3*t6*(-t11-t18+t22+t23+xe12+xe32-xe42*2.)*(-1./16.)])
    N=np.concatenate([mt1, mt2], axis=0)   # (12, 1) when xi are (1,) arrays
    return N                                # shape (12,1) or (12,) depending on input


def _detFisop_4node(in1, in2, in3, in4, in5):
    """Jacobian determinant for 4-node isoparametric element."""
    in1=np.atleast_2d(in1).reshape(2,-1)
    in2=np.atleast_2d(in2).reshape(2,-1)
    in3=np.atleast_2d(in3).reshape(2,-1)
    in4=np.atleast_2d(in4).reshape(2,-1)
    in5=np.atleast_2d(in5).reshape(2,-1)
    xe11=in2[0,:]; xe12=in2[1,:]
    xe21=in3[0,:]; xe22=in3[1,:]
    xe31=in4[0,:]; xe32=in4[1,:]
    xe41=in5[0,:]; xe42=in5[1,:]
    xi1=in1[0,:];  xi2=in1[1,:]
    dN1_dxi1=-0.25*(1.-xi2); dN2_dxi1= 0.25*(1.-xi2)
    dN3_dxi1= 0.25*(1.+xi2); dN4_dxi1=-0.25*(1.+xi2)
    dN1_dxi2=-0.25*(1.-xi1); dN2_dxi2=-0.25*(1.+xi1)
    dN3_dxi2= 0.25*(1.+xi1); dN4_dxi2= 0.25*(1.-xi1)
    dx_dxi1=dN1_dxi1*xe11+dN2_dxi1*xe21+dN3_dxi1*xe31+dN4_dxi1*xe41
    dy_dxi1=dN1_dxi1*xe12+dN2_dxi1*xe22+dN3_dxi1*xe32+dN4_dxi1*xe42
    dx_dxi2=dN1_dxi2*xe11+dN2_dxi2*xe21+dN3_dxi2*xe31+dN4_dxi2*xe41
    dy_dxi2=dN1_dxi2*xe12+dN2_dxi2*xe22+dN3_dxi2*xe32+dN4_dxi2*xe42
    return dx_dxi1*dy_dxi2 - dx_dxi2*dy_dxi1


# For Bast: import from LN_code_python (must be on sys.path) -----------------
try:
    from LN_code_python import Bast_kirchoff_func as _Bast_kirchoff_func
except ImportError:
    raise ImportError(
        "Place LN_code_python.py in the same folder as this script "
        "so that Bast_kirchoff_func can be imported.")


# =============================================================================
# 1. Material & loading parameters
# =============================================================================
E_al      = 80e9        # [Pa]
nu_al     = 0.2
sy_al     = 200e6       # yield stress [Pa]
alpha_al  = 20e-6       # CTE [1/K]

rho_snow  = 500.0       # wet compacted snow density [kg/m³]
g         = 9.81        # [m/s²]
h_snow    = 0.25        # [m]
angle_deg = 15.0
alpha_r   = np.radians(angle_deg)

# Snow pressure per unit horizontal area
q0 = rho_snow * g * h_snow          # = 1226.25 N/m²

# Loads resolved to the inclined plate (per unit PLATE area)
#   - Transverse (normal to plate)  : q̄ = q0 cos²α
#   - In-plane (down the slope, +x) : f̄x = q0 cosα sinα
q_bar  = q0 * np.cos(alpha_r)**2                    # [N/m²]
fx_bar = q0 * np.cos(alpha_r) * np.sin(alpha_r)     # [N/m²]

print(f"Snow: q0 = {q0:.2f} N/m²")
print(f"  Transverse  q̄  = {q_bar:.2f} N/m²")
print(f"  In-plane   f̄x  = {fx_bar:.2f} N/m²")

# Design variable – plate thickness (tune in Task 1g)
h_plate = 0.003         # 3 mm initial guess

print(f"\nPlate thickness: {h_plate*1e3:.1f} mm")


# =============================================================================
# 2. Load mesh (generated by MATLAB rectMesh and saved as testfil.mat)
#
#    rectMesh settings used:
#      xmin=0, xmax=0.75, ymin=0, ymax=0.50, nelx=15, nely=10
#    Plate: 0.75 m (down the slope) × 0.50 m (across the roof)
# =============================================================================
data    = sio.loadmat('testfil.mat', squeeze_me=True, struct_as_record=False)
mesh_m  = data['mesh']          # MATLAB: 4 × nel  → Python: (4, nel) after squeeze
Coord   = data['coord']         # (nnodes, 2)  [x, y] coordinates
# Edof may be stored as a (sparse) matrix in the .mat file; ensure dense ndarray
Edof_ip = data['Edof_ip']
Edof_oop= data['Edof_oop']
import scipy.sparse as _sps
if _sps.issparse(Edof_ip):
    Edof_ip = Edof_ip.toarray()
if _sps.issparse(Edof_oop):
    Edof_oop = Edof_oop.toarray()
Edof_ip = Edof_ip.astype(int)
Edof_oop = Edof_oop.astype(int)

# node_idx[el, :] = 4 zero-indexed node numbers for element el
node_idx = (mesh_m.T - 1).astype(int)   # (nel, 4)

nel    = node_idx.shape[0]
nnodes = Coord.shape[0]
ndof   = 5 * nnodes

print(f"\nMesh: {nel} elements, {nnodes} nodes, {ndof} total DOFs")


# =============================================================================
# 3. Helper functions
# =============================================================================

def hooke_plane_stress(E, nu):
    """3×3 plane-stress constitutive matrix D."""
    f = E / (1.0 - nu**2)
    return f * np.array([[1., nu, 0.],
                          [nu, 1., 0.],
                          [0., 0., (1.-nu)/2.]])


def Bu_and_detJ(xi1v, xi2v, xe_nodes):
    """
    In-plane B matrix (3×8) and Jacobian determinant for the 4-node
    bilinear element.
    xe_nodes : (4,2) nodal coords.
    """
    dN_dxi = 0.25 * np.array([
        [-(1.-xi2v),  (1.-xi2v), (1.+xi2v), -(1.+xi2v)],
        [-(1.-xi1v), -(1.+xi1v),(1.+xi1v),  (1.-xi1v)]
    ])                              # (2,4)
    J    = dN_dxi @ xe_nodes        # (2,2)
    detJ = float(np.linalg.det(J))
    dN_dx = np.linalg.inv(J) @ dN_dxi  # (2,4)  [row0=dNi/dx, row1=dNi/dy]

    B_u = np.zeros((3, 8))
    for k in range(4):
        B_u[0, 2*k  ] = dN_dx[0, k]    # ∂N/∂x → εxx
        B_u[1, 2*k+1] = dN_dx[1, k]    # ∂N/∂y → εyy
        B_u[2, 2*k  ] = dN_dx[1, k]    # ∂N/∂y → γxy
        B_u[2, 2*k+1] = dN_dx[0, k]    # ∂N/∂x → γxy
    return B_u, detJ


def Nu_inplane(xi1v, xi2v):
    """Shape function matrix (2×8) for in-plane bilinear element."""
    Nv = [0.25*(1.-xi1v)*(1.-xi2v),
          0.25*(1.+xi1v)*(1.-xi2v),
          0.25*(1.+xi1v)*(1.+xi2v),
          0.25*(1.-xi1v)*(1.+xi2v)]
    N_u = np.zeros((2, 8))
    for k, Nk in enumerate(Nv):
        N_u[0, 2*k  ] = Nk
        N_u[1, 2*k+1] = Nk
    return N_u


# 2×2 Gauss points and weights (all weights = 1)
_gp   = 1.0/np.sqrt(3.)
_xi_gp = np.array([[-_gp,-_gp], [_gp,-_gp], [_gp,_gp], [-_gp,_gp]])


# =============================================================================
# 4. Element routine (Task 1c / 1d)
#
# Returns the 4 element matrices:
#   K_uu  (8×8)   in-plane membrane stiffness
#   K_ww  (12×12) Kirchhoff bending stiffness
#   f_u   (8×1)   in-plane load vector  (snow tangential component)
#   f_w   (12×1)  bending load vector   (snow transverse component)
# =============================================================================
def kirchhoff_plate_element(ex, ey, h_pl, E, nu, q_transverse, fx_inplane):
    """
    Combined Kirchhoff plate element matrices.

    Parameters
    ----------
    ex, ey       : (4,) nodal x and y coordinates [m]
    h_pl         : plate thickness [m]
    E, nu        : material parameters
    q_transverse : uniform transverse pressure [N/m²]  (→ f_w)
    fx_inplane   : uniform in-plane load in x-dir [N/m²] (→ f_u)

    Returns
    -------
    K_uu (8,8), K_ww (12,12), f_u (8,1), f_w (12,1)
    """
    D      = hooke_plane_stress(E, nu)
    D_bar  = (h_pl**3 / 12.0) * D       # flexural stiffness matrix

    xe_nodes = np.column_stack((ex, ey))  # (4,2)
    n1 = np.array([[ex[0]], [ey[0]]])
    n2 = np.array([[ex[1]], [ey[1]]])
    n3 = np.array([[ex[2]], [ey[2]]])
    n4 = np.array([[ex[3]], [ey[3]]])

    K_uu = np.zeros((8,  8))
    K_ww = np.zeros((12, 12))
    f_u  = np.zeros((8,  1))
    f_w  = np.zeros((12, 1))

    for i in range(4):                   # 2×2 Gauss integration
        xi1v, xi2v = _xi_gp[i]
        xin = np.array([[xi1v], [xi2v]])

        # ── in-plane (membrane) ──────────────────────────────────────────
        B_u, detJ = Bu_and_detJ(xi1v, xi2v, xe_nodes)
        N_u       = Nu_inplane(xi1v, xi2v)
        f_body    = np.array([[fx_inplane], [0.0]])

        K_uu += B_u.T @ (h_pl * D) @ B_u * detJ       # weight = 1
        f_u  += N_u.T @ f_body * detJ                  # N/m² × m² → N

        # ── bending (Kirchhoff) ──────────────────────────────────────────
        _, Bast, detFis = _Bast_kirchoff_func(xin, n1, n2, n3, n4)
        detFis_val = float(np.squeeze(detFis))

        N_w = _N_kirchoff_func(xin, n1, n2, n3, n4)
        N_w_col = N_w.reshape(-1, 1)               # ensure (12,1)

        K_ww += Bast.T @ D_bar @ Bast * detFis_val
        f_w  += N_w_col * q_transverse * detFis_val

    return K_uu, K_ww, f_u, f_w


# =============================================================================
# 5. Assembly
# =============================================================================
K_glob = np.zeros((ndof, ndof))
f_glob = np.zeros(ndof)

print("\nAssembling global stiffness and load vector …")
for el in range(nel):
    ex = Coord[node_idx[el, :], 0]
    ey = Coord[node_idx[el, :], 1]

    # Zero-indexed global DOFs for this element
    d_ip  = Edof_ip [el, 1:] - 1   # (8,)
    d_oop = Edof_oop[el, 1:] - 1   # (12,)

    K_uu, K_ww, f_u, f_w = kirchhoff_plate_element(
        ex, ey, h_plate, E_al, nu_al, q_bar, fx_bar)

    K_glob[np.ix_(d_ip,  d_ip )] += K_uu
    K_glob[np.ix_(d_oop, d_oop)] += K_ww
    f_glob[d_ip ] += f_u.flatten()
    f_glob[d_oop] += f_w.flatten()

print("  Assembly complete.")


# =============================================================================
# Task 1d – load-vector verification
#   Total transverse force from f_w should equal q̄ × plate area.
#   Total in-plane force in x from f_u should equal f̄x × plate area.
# =============================================================================
plate_area = (Coord[:,0].max() - Coord[:,0].min()) * \
             (Coord[:,1].max() - Coord[:,1].min())

# w-DOF indices are at global positions 2, 7, 12, …  (5*n + 2)
w_dof_mask  = np.arange(2, ndof, 5)
ux_dof_mask = np.arange(0, ndof, 5)

sum_fw  = f_glob[w_dof_mask ].sum()
sum_fux = f_glob[ux_dof_mask].sum()

print(f"\nLoad vector verification:")
print(f"  Sum of nodal w-forces   = {sum_fw:.4f} N   "
      f"| expected {q_bar*plate_area:.4f} N")
print(f"  Sum of nodal ux-forces  = {sum_fux:.4f} N   "
      f"| expected {fx_bar*plate_area:.4f} N")


# =============================================================================
# 6. Boundary conditions  (Task 1a)
#
#   Clamped edges (3):
#     top   (x = 0)     → ridge
#     left  (y = 0)     → side
#     right (y = ymax)  → side
#   All 5 DOFs per node = 0.
#
#   Gliding edge (1):
#     bottom (x = xmax) → closest to ground
#   w = 0  (DOF 2),  θx = ∂w/∂x = 0  (DOF 4) per node.
#   ux, uy, θy remain FREE.
# =============================================================================
x_all, y_all = Coord[:, 0], Coord[:, 1]
x_min, x_max = x_all.min(), x_all.max()
y_min, y_max = y_all.min(), y_all.max()
tol = 1e-10

nodes_top   = np.where(x_all < x_min + tol)[0]   # ridge (x=0)
nodes_left  = np.where(y_all < y_min + tol)[0]   # left side (y=0)
nodes_right = np.where(y_all > y_max - tol)[0]   # right side (y=ymax)
nodes_bot   = np.where(x_all > x_max - tol)[0]   # gliding (x=xmax)

clamped_nodes = np.unique(np.concatenate([nodes_top, nodes_left, nodes_right]))

prescribed = set()
# Clamped: all 5 DOFs = 0
for n in clamped_nodes:
    for d in range(5):
        prescribed.add(5*n + d)
# Gliding edge: w (DOF+2) and θx (DOF+4)
for n in nodes_bot:
    prescribed.add(5*n + 2)
    prescribed.add(5*n + 4)

prescribed = np.array(sorted(prescribed), dtype=int)
free       = np.setdiff1d(np.arange(ndof), prescribed)

print(f"\nBoundary conditions:")
print(f"  Prescribed DOFs : {len(prescribed)}")
print(f"  Free DOFs       : {len(free)}")


# =============================================================================
# 7. Solve
# =============================================================================
K_ff = K_glob[np.ix_(free, free)]
f_f  = f_glob[free]

print("\nSolving linear system …")
# Try direct solve; if K_ff is singular, provide diagnostics and a
# small-Tikhonov-regularized fallback so the script can continue.
try:
    a_free = sla.solve(K_ff, f_f)
except Exception as e:
    print("\nLinear solve failed:", e)
    print("Computing diagnostics for K_ff (SVD)...")
    # SVD diagnostics
    U, S, VT = np.linalg.svd(K_ff)
    print("  matrix shape:", K_ff.shape)
    print("  largest singular values:", S[:6])
    print("  smallest singular values:", S[-6:])
    # Identify near-nullspace
    sv_tol = 1e-12 * S[0] if S.size and S[0] != 0 else 1e-12
    null_idx = np.where(S < sv_tol)[0]
    print(f"  singular values < {sv_tol:.3e}: {len(null_idx)}")
    if len(null_idx) > 0:
        nullspace = VT.T[:, null_idx]
        for i in range(nullspace.shape[1]):
            vec = nullspace[:, i]
            largest = np.abs(vec).argsort()[::-1][:8]
            print(f"  nullvec {i}: top DOFs indices (local to K_ff):", largest)
    # Attempt Tikhonov regularization fallback
    diag_mean = np.mean(np.abs(np.diag(K_ff)))
    alpha = 1e-8 * diag_mean if diag_mean > 0 else 1e-12
    print(f"Attempting regularized solve with alpha={alpha:.3e}...")
    K_reg = K_ff + alpha * np.eye(K_ff.shape[0])
    a_free = sla.solve(K_reg, f_f)
    print("Regularized solve complete (results approximate).")

a = np.zeros(ndof)
a[free] = a_free
print("  Solve complete.")


# =============================================================================
# 8. Extract displacement fields
# =============================================================================
w_nodes  = a[2::5]    # out-of-plane deflection at every node
ux_nodes = a[0::5]
uy_nodes = a[1::5]
ty_nodes = a[3::5]    # θy
tx_nodes = a[4::5]    # θx

w_max = np.abs(w_nodes).max()
print(f"\n{'='*60}")
print(f"  Max |w|  = {w_max*1e3:.3f} mm   (limit: 25 mm)")
if w_max*1e3 <= 25.0:
    print("  Deflection criterion:  SATISFIED ✓")
else:
    print("  Deflection criterion:  VIOLATED  ✗  → increase thickness")
print(f"{'='*60}")


# =============================================================================
# 9. Displacement contour plots  (Task 1e)
# =============================================================================
def element_average(nodal_field):
    """Compute element-average of a nodal field for patch colouring."""
    return nodal_field[node_idx].mean(axis=1)

polygons = Coord[node_idx]   # (nel, 4, 2)

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
fig.suptitle(f"Displacements  (h = {h_plate*1e3:.1f} mm, snow load)", fontsize=13)

configs = [
    (w_nodes*1e3,    'w [mm]',   'RdBu_r'),
    (ux_nodes*1e6,   'ux [μm]',  'viridis'),
    (uy_nodes*1e6,   'uy [μm]',  'viridis'),
]
for ax, (field, label, cmap) in zip(axes, configs):
    el_vals = element_average(field)
    pc = PolyCollection(polygons, array=el_vals,
                        cmap=cmap, edgecolors='none')
    ax.add_collection(pc)
    ax.autoscale()
    ax.set_aspect('equal')
    ax.set_title(label)
    ax.set_xlabel('x [m]  (down slope)')
    ax.set_ylabel('y [m]')
    plt.colorbar(pc, ax=ax)

plt.tight_layout()
plt.savefig('task1_displacements.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: task1_displacements.png")


# =============================================================================
# 10. Stress computation at integration points  (Task 1f)
#
# At each of the 4 Gauss points (ξ1,ξ2) ∈ {±1/√3}² and at thickness
# coordinate z, the total in-plane strain is
#
#     ε(z) = ε⁰  −  z · κ
#
# where  ε⁰ = B_u · aᵤ   (membrane)
#         κ  = Bast · aω  (curvature; from Kirchhoff element)
#
# and the Cauchy stress vector (Voigt, plane stress) is
#
#     σ = D · ε(z)  =  [σ₁₁, σ₂₂, σ₁₂]ᵀ
#
# Von Mises effective stress (plane stress, σ₃₃=σ₁₃=σ₂₃=0):
#     σ_vM = √(σ₁₁² − σ₁₁σ₂₂ + σ₂₂² + 3σ₁₂²)
# =============================================================================

def von_mises_ps(sigma):
    """Von Mises for plane-stress σ = [s11, s22, s12]."""
    s11, s22, s12 = sigma
    return np.sqrt(s11**2 - s11*s22 + s22**2 + 3.0*s12**2)


def element_stress_at_z(ex, ey, a_u_el, a_w_el, h_pl, E, nu, z_coord):
    """
    Compute von Mises stress at all 4 Gauss points for one element
    at through-thickness position z.

    Parameters
    ----------
    a_u_el : (8,)  element in-plane DOF values
    a_w_el : (12,) element bending DOF values
    z_coord: z position  (e.g. +h/2, 0, -h/2)

    Returns
    -------
    sigma_vM : (4,)  von Mises stress at each Gauss point [Pa]
    """
    D         = hooke_plane_stress(E, nu)
    xe_nodes  = np.column_stack((ex, ey))
    n1=np.array([[ex[0]],[ey[0]]])
    n2=np.array([[ex[1]],[ey[1]]])
    n3=np.array([[ex[2]],[ey[2]]])
    n4=np.array([[ex[3]],[ey[3]]])

    sigma_vM = np.zeros(4)
    for i in range(4):
        xi1v, xi2v = _xi_gp[i]
        xin = np.array([[xi1v],[xi2v]])

        # Membrane strain
        B_u, _ = Bu_and_detJ(xi1v, xi2v, xe_nodes)
        eps0   = B_u @ a_u_el                          # (3,)

        # Curvature  κ = Bast · aω  (Bast has shape (3,12))
        _, Bast, _ = _Bast_kirchoff_func(xin, n1, n2, n3, n4)
        kappa  = Bast @ a_w_el                         # (3,)

        # Total strain at depth z  (Kirchhoff: ε = ε⁰ - z·κ)
        eps_z  = eps0 - z_coord * kappa

        # Stress and von Mises
        sigma = D @ eps_z
        sigma_vM[i] = von_mises_ps(sigma)

    return sigma_vM


# ── Evaluate stresses for all elements ──────────────────────────────────────
print("\nComputing element stresses at integration points …")

z_levels   = [-h_plate/2.0, 0.0, h_plate/2.0]
z_labels   = ['-h/2 (bottom)', 'z=0 (mid-plane)', '+h/2 (top)']
vM_contour = {}             # dict  z_val → (nel,) array of element-average σ_vM

for z in z_levels:
    el_avg_vM = np.zeros(nel)
    for el in range(nel):
        ex = Coord[node_idx[el,:], 0]
        ey = Coord[node_idx[el,:], 1]

        d_ip  = Edof_ip [el, 1:] - 1
        d_oop = Edof_oop[el, 1:] - 1

        a_u_el = a[d_ip ]
        a_w_el = a[d_oop]

        svm = element_stress_at_z(ex, ey, a_u_el, a_w_el,
                                   h_plate, E_al, nu_al, z)
        el_avg_vM[el] = svm.mean()

    vM_contour[z] = el_avg_vM

print("  Stress computation complete.")


# ── Von Mises contour plots ──────────────────────────────────────────────────
fig2, axes2 = plt.subplots(1, 3, figsize=(16, 4))
fig2.suptitle(
    f"Von Mises effective stress [MPa]  (h = {h_plate*1e3:.1f} mm, snow load)",
    fontsize=13)

sigma_max_overall = 0.0
for ax, (z, lbl) in zip(axes2, zip(z_levels, z_labels)):
    el_vals = vM_contour[z] / 1e6      # Pa → MPa
    sigma_max_overall = max(sigma_max_overall, el_vals.max())

    pc = PolyCollection(polygons, array=el_vals,
                        cmap='hot_r', edgecolors='none')
    ax.add_collection(pc)
    ax.autoscale()
    ax.set_aspect('equal')
    ax.set_title(f'z = {lbl}')
    ax.set_xlabel('x [m]')
    ax.set_ylabel('y [m]')
    plt.colorbar(pc, ax=ax)

plt.tight_layout()
plt.savefig('task1_stress_vonMises.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: task1_stress_vonMises.png")


# =============================================================================
# 11. Design check  (Task 1g)
# =============================================================================
SF_yield = sy_al / sigma_max_overall
print(f"\n{'='*60}")
print(f"DESIGN CHECK  (h = {h_plate*1e3:.1f} mm)")
print(f"{'='*60}")
print(f"  Max von Mises stress  = {sigma_max_overall:.2f} MPa")
print(f"  Yield stress          = {sy_al/1e6:.1f} MPa")
print(f"  Safety factor (yield) = {SF_yield:.2f}  (required ≥ 2)")
print(f"  Max deflection        = {w_max*1e3:.3f} mm  (required ≤ 25 mm)")

criteria_ok = (SF_yield >= 2.0) and (w_max*1e3 <= 25.0)
if criteria_ok:
    print(f"\n  ✓  Both criteria SATISFIED for h = {h_plate*1e3:.1f} mm")
else:
    if SF_yield < 2.0:
        print("  ✗  Stress criterion NOT satisfied → increase h")
    if w_max*1e3 > 25.0:
        print("  ✗  Deflection criterion NOT satisfied → increase h")

print(f"{'='*60}")

# ── Optional: sweep over thicknesses to find minimum h ──────────────────────
print("\nThickness sweep (re-assembles for each h):")
print(f"{'h [mm]':>10} {'w_max [mm]':>12} {'σ_vM_max [MPa]':>16} {'SF':>8} {'OK?':>6}")
for h_try in [1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0]:
    h_try_m = h_try * 1e-3
    # Quick re-assembly (same BC structure)
    K_t = np.zeros((ndof, ndof)); f_t = np.zeros(ndof)
    for el in range(nel):
        ex = Coord[node_idx[el,:],0]; ey = Coord[node_idx[el,:],1]
        d_ip  = Edof_ip [el,1:]-1;    d_oop = Edof_oop[el,1:]-1
        Ku, Kw, fu, fw = kirchhoff_plate_element(
            ex, ey, h_try_m, E_al, nu_al, q_bar, fx_bar)
        K_t[np.ix_(d_ip, d_ip )] += Ku
        K_t[np.ix_(d_oop,d_oop)] += Kw
        f_t[d_ip ] += fu.flatten(); f_t[d_oop] += fw.flatten()
    a_t = np.zeros(ndof)
    a_t[free] = sla.solve(K_t[np.ix_(free,free)], f_t[free])
    wmax_t = np.abs(a_t[2::5]).max()
    # Stress at z=+h/2 (top, often governing for clamped edge)
    svm_max_t = 0.0
    for el in range(nel):
        ex=Coord[node_idx[el,:],0]; ey=Coord[node_idx[el,:],1]
        d_ip=Edof_ip[el,1:]-1; d_oop=Edof_oop[el,1:]-1
        svm = element_stress_at_z(ex,ey,a_t[d_ip],a_t[d_oop],
                                   h_try_m,E_al,nu_al, h_try_m/2.0)
        svm_max_t = max(svm_max_t, svm.max())
    sf_t = sy_al / svm_max_t
    ok = '✓' if (sf_t >= 2.0 and wmax_t*1e3 <= 25.0) else '✗'
    print(f"{h_try:>10.1f} {wmax_t*1e3:>12.3f} {svm_max_t/1e6:>16.2f} "
          f"{sf_t:>8.2f} {ok:>6}")
